import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.getAll.useQuery()

  return (
    <>
      <Head>
        <title>Qavi - Todo App</title>
        <meta name="It is a typescript developer test for Qavi company. So the test is a Todo List." content="It is a typescript developer test for Qavi company. So the test is a Todo List.Generated by create-t3-app" />
      </Head>

      <main className="text-white flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-2xl font-semibold">My Tasks List</h1>
      </main>
    </>
  );
};

export default Home;
