import { type NextPage } from "next";
import Head from "next/head";

import { Header } from "../components/Header";
import { Todos } from "../components/Todos";
import { CreateTodo } from "~/components/CreateTodo";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Qavi - Todo App</title>
        <meta
          name="It is a typescript developer test for Qavi company. So the test is a Todo List."
          content="It is a typescript developer test for Qavi company. So the test is a Todo List.Generated by create-t3-app"
        />
      </Head>


      <div className="text-white flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Header />
        <h1 className="text-2xl font-semibold">My Tasks List</h1>

        <div className="text-black flex flex-col max-h-[350px] w-[600px] relative mx-auto mt-8 rounded-lg bg-white p-2 shadow-[0_1px_7px_0px_rgba(250,250,250,0.5)]">
          <div className="h-[50px] flex flex-row justify-between">
            <input
              className="text-[20px] font-medium w-3/4"
              type="text" name="title" id="title"
              placeholder="Title..."
            />

            <div>
              <button>
                📝
              </button>

              <button>
                ✖️
              </button>
            </div>
          </div>

          <div className="overflow-y-auto">
            <Todos />
          </div>
          <CreateTodo />
        </div>
      </div>
    </>
  );
};

export default Home;
